Repository celesteoficial/java-library, pull requests merged in 2021-06, with the labels that each got.

#12 Fix inventory
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/Menu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/AbstractPaginator.java
Labels: bug

#13 Added: Context
  spigot/src/main/java/com/celeste/library/spigot/AbstractBukkitPlugin.java
  spigot/src/main/java/com/celeste/library/spigot/exception/MenuException.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuItem.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/annotation/Menu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/AbstractContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/Context.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/event/InventoryRenderEvent.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/CloseContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/DragContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/OpenContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/RenderContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/impl/MenuPaginator.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/EventFilters.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/EventWaiter.java
Labels: enhancement

#14 Fix inventory
  LICENSE.md
  README.md
  bungeecord/src/main/java/com/celeste/library/bungee/AbstractBungeePlugin.java
  bungeecord/src/main/java/com/celeste/library/bungee/annotation/CommandHolder.java
  core/src/main/java/com/celeste/library/core/model/entity/Cooldown.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/ConcurrentRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/LinkedRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/MapRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/TableRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/WeakRegistry.java
  core/src/main/java/com/celeste/library/core/util/formatter/DateFormatter.java
  gradlew
  spigot/src/main/java/com/celeste/library/spigot/AbstractBukkitPlugin.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuItem.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/annotation/Menu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/AbstractContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/Context.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/event/InventoryRenderEvent.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/CloseContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/DragContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/OpenContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/impl/RenderContext.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/AbstractPaginator.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/Paginator.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/impl/MenuPaginator.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/impl/PaginatorImpl.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemBuilder.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemGiantCreator.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemSerializer.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/type/EnchantmentType.java
  spigot/src/main/java/com/celeste/library/spigot/util/menu/BorderShape.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/EventController.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/EventFilters.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/EventWaiter.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/wrapper/AbstractEvent.java
  spigot/src/main/java/com/celeste/library/spigot/view/event/wrapper/impl/InventoryRenderEvent.java
  spigot/src/main/java/com/celeste/library/spigot/view/listener/MenuListener.java
Labels: bug

#16 Fixed Paginator and MenuListener errors
  spigot/src/main/java/com/celeste/library/spigot/view/listener/MenuListener.java
Labels: bug

#17 @Menu annotation is optional and default cancelOnClick
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/annotation/Menu.java
Labels: enhancement

#24 Multiple fixes to ItemBuilder and Monitor
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemBuilder.java
  spigot/src/main/java/com/celeste/library/spigot/view/listener/MonitorListener.java
Labels: bug, enhancement

#25 added: new useful methods
  core/src/main/java/com/celeste/library/core/util/pattern/RegexPattern.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuItem.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/entity/Context.java
Labels: enhancement

#28 Thread Pool instances - Error
  bungeecord/src/main/java/com/celeste/library/bungee/AbstractBungeePlugin.java
  spigot/src/main/java/com/celeste/library/spigot/AbstractBukkitPlugin.java
Labels: bug
