Repository celesteoficial/java-library, pull requests merged in 2021-07, with the labels that each got.

#29 Inventory error
  build.gradle
  bungeecord/src/main/java/com/celeste/library/bungee/AbstractBungeePlugin.java
  core/src/main/java/com/celeste/library/core/adapter/impl/jackson/JacksonAdapter.java
  core/src/main/java/com/celeste/library/core/model/entity/Data.java
  core/src/main/java/com/celeste/library/core/util/Logger.java
  core/src/main/java/com/celeste/library/core/util/builder/StringBuilder.java
  core/src/main/java/com/celeste/library/core/util/formatter/DateFormatter.java
  core/src/main/java/com/celeste/library/core/util/formatter/PrefixFormatter.java
  core/src/main/java/com/celeste/library/core/util/formatter/RomanFormatter.java
  core/src/main/java/com/celeste/library/core/util/formatter/StringFormatter.java
  spigot/src/main/java/com/celeste/library/spigot/AbstractBukkitPlugin.java
  spigot/src/main/java/com/celeste/library/spigot/model/entity/AbstractBungeeConnection.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/paginator/impl/MenuPaginator.java
  spigot/src/main/java/com/celeste/library/spigot/util/EntityInjector.java
  spigot/src/main/java/com/celeste/library/spigot/util/InventoryInjector.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemGiantCreator.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/type/DyeType.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/type/WoolType.java
  spigot/src/main/java/com/celeste/library/spigot/util/monitor/ChatMonitor.java
  spigot/src/main/java/com/celeste/library/spigot/view/listener/MonitorListener.java
Labels: bug

#32 added: json builder methods
  spigot/src/main/java/com/celeste/library/spigot/util/EntityInjector.java
  spigot/src/main/java/com/celeste/library/spigot/util/item/ItemGiantCreator.java
  spigot/src/main/java/com/celeste/library/spigot/util/message/Json.java
Labels: enhancement

#33 added: Item annotation, update: Reflection
  core/src/main/java/com/celeste/library/core/util/Reflection.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/AbstractMenu.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuHolder.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/MenuItem.java
  spigot/src/main/java/com/celeste/library/spigot/model/menu/annotation/Item.java
Labels: enhancement

#36 Strings
  core/src/main/java/com/celeste/library/core/util/builder/DateBuilder.java
  core/src/main/java/com/celeste/library/core/util/builder/RegexBuilder.java
  core/src/main/java/com/celeste/library/core/util/builder/StringBuilder.java
  core/src/main/java/com/celeste/library/core/util/formatter/DateFormatter.java
  core/src/main/java/com/celeste/library/core/util/formatter/type/TimeLanguage.java
  core/src/main/java/com/celeste/library/core/util/matcher/StringMatcher.java
  core/src/main/java/com/celeste/library/core/util/pattern/RegexPattern.java
Labels: bug, enhancement

#37 Maps
  .gitignore
  core/src/main/java/com/celeste/library/core/collection/Collection.java
  core/src/main/java/com/celeste/library/core/inflexible/AbstractInflexible.java
  core/src/main/java/com/celeste/library/core/inflexible/Inflexible.java
  core/src/main/java/com/celeste/library/core/inflexible/impl/InflexibleHash.java
  core/src/main/java/com/celeste/library/core/model/registry/AbstractRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/MapBuilder.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/ConcurrentRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/LinkedRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/MapRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/TableRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/TreeRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/impl/WeakRegistry.java
  core/src/main/java/com/celeste/library/core/model/registry/type/MapType.java
  core/src/main/java/com/celeste/library/core/registry/AbstractRegistry.java
  core/src/main/java/com/celeste/library/core/registry/MapBuilder.java
  core/src/main/java/com/celeste/library/core/registry/Registry.java
  core/src/main/java/com/celeste/library/core/registry/entry/Entry.java
  core/src/main/java/com/celeste/library/core/registry/entry/impl/SimpleEntry.java
  core/src/main/java/com/celeste/library/core/registry/entry/impl/SimpleImmutableEntry.java
  core/src/main/java/com/celeste/library/core/registry/impl/LinkedRegistry.java
  core/src/main/java/com/celeste/library/core/registry/impl/MapRegistry.java
  core/src/main/java/com/celeste/library/core/registry/iterator/HashIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/LinkedHashIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/hash/EntryIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/hash/KeyIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/hash/ValueIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/linked/LinkedKeyIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/linked/LinkedNodeIterator.java
  core/src/main/java/com/celeste/library/core/registry/iterator/linked/LinkedValueIterator.java
  core/src/main/java/com/celeste/library/core/registry/nodes/Node.java
  core/src/main/java/com/celeste/library/core/registry/nodes/TreeNode.java
  core/src/main/java/com/celeste/library/core/registry/nodes/impl/LinkedNode.java
  core/src/main/java/com/celeste/library/core/registry/set/EntrySet.java
  core/src/main/java/com/celeste/library/core/registry/set/KeySet.java
  core/src/main/java/com/celeste/library/core/registry/set/Values.java
  core/src/main/java/com/celeste/library/core/registry/set/linked/LinkedNodeSet.java
  core/src/main/java/com/celeste/library/core/registry/splitter/EntrySpliterator.java
  core/src/main/java/com/celeste/library/core/registry/splitter/KeySpliterator.java
  core/src/main/java/com/celeste/library/core/registry/splitter/MapSpliterator.java
  core/src/main/java/com/celeste/library/core/registry/splitter/ValueSpliterator.java
  core/src/main/java/com/celeste/library/core/registry/type/KeyType.java
  core/src/main/java/com/celeste/library/core/registry/type/MapType.java
  core/src/main/java/com/celeste/library/core/util/builder/DateBuilder.java
  core/src/main/java/com/celeste/library/core/util/builder/StringBuilder.java
  settings.gradle
Labels: enhancement

#42 added: Scoreboard module. Credits to @Deser
  spigot/src/main/java/com/celeste/library/spigot/model/scoreboard/Score.java
Labels: enhancement
